import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Next.js App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ maxWidth: "800px", margin: "0 auto", padding: "20px" }}>
        <h1>Welcome to Next.js!</h1>
        <p>Get started by editing this page.</p>
      </main>
    </>
  );
}
