import { test, expect } from '@playwright/test';

test.describe('Index Page', () => {
  test('should load the home page', async ({ page }) => {
    await page.goto('/');
    
    // Check page title
    await expect(page).toHaveTitle('Next.js App');
    
    // Check main heading
    await expect(page.getByRole('heading', { name: 'Welcome to Next.js!', level: 1 })).toBeVisible();
    
    // Check welcome text
    await expect(page.getByText('Get started by editing this page.')).toBeVisible();
  });

  test('should have correct meta description', async ({ page }) => {
    await page.goto('/');
    
    // Check meta description
    const metaDescription = page.locator('meta[name="description"]');
    await expect(metaDescription).toHaveAttribute('content', 'Generated by create next app');
  });

  test('should have favicon', async ({ page }) => {
    await page.goto('/');
    
    // Check favicon link
    const favicon = page.locator('link[rel="icon"]');
    await expect(favicon).toHaveAttribute('href', '/favicon.ico');
  });
});