name: CI

on:
  pull_request:

jobs:
  Lint:
    runs-on: ubuntu-18.04

    steps:
      - uses: ./.github/actions/setup
      - run: pnpm lint

  E2ETests:
    runs-on: ubuntu-18.04

    steps:
      - uses: ./.github/actions/setup
      - run: npx playwright install chromium
      - run: pnpm test:e2e
